version: "3.9"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: cabbage
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: .
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - APP_HOST=0.0.0.0
      - APP_PORT=8000
    depends_on:
      - db
    ports:
      - "8000:8000"
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]

  telegram-bot:
    build: .
    env_file:
      - .env
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db
    command: ["python", "-m", "app.telegram.run_bot"]

volumes:
  db_data:
