"""change qty to integer

Revision ID: dd5f84b0d2d0
Revises: 83a4b57ca6c3
Create Date: 2025-10-05 11:01:11.239019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd5f84b0d2d0'
down_revision: Union[str, Sequence[str], None] = '83a4b57ca6c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('qty', sa.Integer(), nullable=False))
    op.drop_column('products', 'stock_quantity')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('stock_quantity', sa.NUMERIC(precision=12, scale=3), autoincrement=False, nullable=False))
    op.drop_column('products', 'qty')
    # ### end Alembic commands ###
