"""Add username column to users

Revision ID: ec08a6c8e959
Revises: d56bc6277e3a
Create Date: 2025-10-05 14:29:01.783056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec08a6c8e959'
down_revision: Union[str, Sequence[str], None] = 'd56bc6277e3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'addresses', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'addresses', type_='foreignkey')
    # ### end Alembic commands ###
